version: '3'
services:
  node:
    container_name: node_notation
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './src/app:/home/node/app'
    links:
      - mongo
    networks:
      - my-network
  mongo:
    container_name: mongo_notation
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
  web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./src/front:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
        - my-network
networks:
  my-network:
    driver: bridge
